### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by dujuku** [Shapeways/hubot-profiler#2]
We're using Apache 2.0 in package.json. Should add the actual text of the license to the project.

**Comment by EllingtonKirby** [comment]
Added the apache2.0 license under license.txt

**Comment by justiniso** [comment]
Common convention is to call the file `LICENSE` with no extension. Also, remember to close the issue when done.

**Comment by EllingtonKirby** [comment]
Gotcha, will fix
